---
name: Create Release

env:
  # https://github.com/actions/virtual-environments/issues/1499
  MAVEN_CLI_OPTS: '-ntp --batch-mode --errors --fail-at-end --show-version -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dstyle.color=always'

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Default version to use when preparing a release."
        required: true
        default: "X.Y.Z"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git User

      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17

      - run: ./mvnw ${MAVEN_CLI_OPTS} release:prepare -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -Drelease.signTag=false
#
#      - name: Create Pull Request
#        id: pr
#        uses: peter-evans/create-pull-request@v3
#        with:
#          title: "Release ${{ github.event.inputs.releaseVersion }}"
#          author: "github-actions <41898282+github-actions[bot]@users.noreply.github.com>"
#          committer: "github-actions <41898282+github-actions[bot]@users.noreply.github.com>"
#          commit-message: "Release ${{ github.event.inputs.releaseVersion }}"
#          branch: "release/${{ github.event.inputs.releaseVersion }}"
#          delete-branch: true
#          labels: automerge,release
#
#      - uses: peter-evans/enable-pull-request-automerge@v1
#        with:
#          token: ${{ secrets.PAT }}
#          pull-request-number: 1
#
#      - name: "Merge pull request"
#        uses: "pascalgn/automerge-action@v0.14.3"
#        env:
#          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
#          MERGE_METHOD: "rebase"
#          PULL_REQUEST: "${{ steps.pr.outputs.pull-request-number }}"
